#!/bin/bash

options=(
    style=round
    width=4.0
    hidpi=on
    ax_focus=on
    active_color=0xff686868
    inactive_color=0xff101010
    blacklist="Finder,Safari,Spotlight,System Settings,Activity Monitor,Preview,Messages,FaceTime,Music,Photos,Calendar,Reminders,App Store,Notes,Mail,Screen Studio,iPhone Mirroring,SketchyBar,SystemUIServer"
)

/opt/homebrew/bin/borders "${options[@]}"
